apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http-headers
spec:
  selector:
    matchLabels:
      app: http-headers
  replicas: 2
  template:
    metadata:
      labels:
        app: http-headers
    spec:
      containers:
      - image: quay.io/k8start/http-headers
        imagePullPolicy: Always
        name: http-headers
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: http-headers
spec:
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: http-headers
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-headers
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - headers.example.com
    secretName: tls-headers-example-com
  rules:
  - host: headers.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: http-headers
              port:
                number: 80
