apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http-headers
spec:
  selector:
    matchLabels:
      app: golang-http-headers
  replicas: 2
  template:
    metadata:
      labels:
        app: golang-http-headers
    spec:
      containers:
      - image: quay.io/examples/go-http-headers:master
        imagePullPolicy: Always
        name: golang-http-headers
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: golang-http-headers
spec:
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: golang-http-headers
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: golang-http-headers
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - headers.example.com
    secretName: tls-headers-example-com
  rules:
  - host: headers.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: golang-http-headers
          servicePort: 80
