name: Detect Changes

# todo change branch main
on:
  push:
    branches:
      - "main"
  workflow_dispatch:


jobs:

  detect-changes:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'

    steps:

      -
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      # https://github.com/tj-actions/changed-files/blob/main/README.md#inputs
      -
        name: Detect Changes
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c # v44.5.7
        id: changes
        with:
          files: |
            *.go
            *.mod
            *Dockerfile

      # Makefile
      -
        name: Generate Changelog
        run: make generate-changelog-ci
        if: steps.changes.outputs.any_changed == 'true'

      # https://github.com/peter-evans/create-pull-request#action-inputs
      -
        name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "change/${{ github.sha }}"
          commit-message: "new changes"
          title: "maybe new release?"
          delete-branch: true


  release-dispatched:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      -
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: make generate-changelog-ci

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "change/${{ github.sha }}"
          commit-message: "new changes"
          title: "probably new release..."
          delete-branch: true
