name: Detect Changes

# todo change branch main
on:
  push:
    branches:
      - "main"
  workflow_dispatch:


jobs:

  detect-changes:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'

    steps:

      -
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      # https://github.com/tj-actions/changed-files/blob/main/README.md#inputs
      -
        name: Detect Changes
        uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275 # v45.0.1
        id: changes
        with:
          files: |
            *.go
            *.mod
            *Dockerfile

      # Makefile
      -
        name: Generate Changelog
        run: make generate-changelog-ci
        if: steps.changes.outputs.any_changed == 'true'

      # https://github.com/peter-evans/create-pull-request#action-inputs
      -
        name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "change/${{ github.sha }}"
          commit-message: "new changes"
          title: "maybe new release?"
          delete-branch: true


  release-dispatched:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      -
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: make generate-changelog-ci

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "change/${{ github.sha }}"
          commit-message: "new changes"
          title: "probably new release..."
          delete-branch: true
