name: ci

on:
  push:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            quay.io/k8start/http-headers
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: List meta bake-file
        run: |
          cat ${{ steps.meta.outputs.bake-file }}
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        id: build
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect labels
        run: |
          docker inspect --format='{{ .Config.Labels }}' ${{ steps.build.outputs.imageid }}

      - name: List images
        run: |
          docker image ls | grep quay.io/k8start/http-headers

      -
        name: Test
        run: |
          CMD="docker run --rm -i -p 9001:9001 ${{ steps.build.outputs.imageid }} --port=9001" ./test.sh

      -
        name: Build and export to Docker
        # todo only on release?
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          cache-from: |
            type=gha
            type=registry,ref=quay.io/k8start/http-headers
          cache-to: type=gha,mode=max

      - name: Login to GitHub Container Registry
        # todo if not pull request
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

#      -
#        name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: ${{ env.TEST_TAG }}
