name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  Docker:
    name: Test in Docker
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

      -
        name: Build Docker Test Image
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
        id: build
        with:
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Test Docker Image
        run: |
          CMD="docker run --rm -i -p 9001:9001 ${{ steps.build.outputs.imageid }} --port=9001" ./test.sh
