name: Build and Push Docker Images

on:
  push:
#    paths:
#      - "test.sh"
#      - "main.go"
#      - "go.mod"
#      - "Dockerfile"
#      - ".dockerignore"
#      - ".github/**"
    tags:
      - "*"
  workflow_dispatch:

jobs:

  Docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:

      -
        name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      -
        name: Build Docker Test Image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        id: build
        with:
          context: .
          load: true

      -
        name: Test Docker Image
        run: |
          CMD="docker run --rm -i -p 9001:9001 ${{ steps.build.outputs.imageid }} --port=9001" ./test.sh

      - name: Get Docker Image Metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: |
            quay.io/k8start/http-headers
            ghcr.io/bukowa/http-headers
            bukowa/http-headers
          tags: |
            type=schedule
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Login to Docker Hub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ROBOT_TOKEN }}

      - name: Login to GHCR.io Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

#      - name: Get Docker Expire Image Metadata
#        id: meta-expire
#        uses: docker/metadata-action@v4
#        with:
#          images: |
#            quay.io/k8start/http-headers
#          tags: |
#            type=sha

#      -
#        # Push images that expire
#        name: Build and Push Docker Expire Images
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta-expire.outputs.tags }}
#          labels: |
#            quay.expires-after=72h
#            ${{ steps.meta-expire.outputs.labels }}
#          cache-from: |
#            type=gha
#            type=registry,ref=quay.io/k8start/http-headers
#          cache-to: |
#            type=gha,mode=max
#          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x

      -
        # Push other images
        name: Build and Push Docker Images
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        id: build-all
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
          cache-to: |
            type=gha
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
