name: Test

on:
  push:
  pull_request:

jobs:

  Test in Docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      -
        name: Build Docker Test Image
        uses: docker/build-push-action@v3
        id: build
        with:
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Test Docker Image
        run: |
          CMD="docker run --rm -i -p 9001:9001 ${{ steps.build.outputs.imageid }} --port=9001" ./test.sh
